services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 15432:5432
    volumes:
      - pg-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservation

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  pg-db:
